version: '3.4'

services:
  api:
    image: saqibrazzaq/xptrackercs_api
    container_name: xptrackercs_api
    build:
      context: .
      dockerfile: api/Dockerfile
    depends_on:
      - db

  web:
    image: saqibrazzaq/xptrackercs_web
    container_name: xptrackercs_web
    build: ./web
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
    depends_on:
      - api

  db:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: xptrackercs_db