version: '3.4'

services:
  api:
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:80;https://+:443
      ASPNETCORE_HTTPS_PORT: 443
      DOMAIN_NAME: xptrackercs-api.saqibrazzaq.com
      USE_STAGING_SERVER: false
      VIRTUAL_HOST: xptrackercs-api.saqibrazzaq.com
      LETSENCRYPT_HOST: xptrackercs-api.saqibrazzaq.com
      LETSENCRYPT_EMAIL: "saqibrazzaq@gmail.com"
    expose:
      - 80
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    networks:
      - nginx-proxy
      - xptrackercs_db

  db:
    volumes:
      - db_data:/var/opt/mssql/data
    environment:
      SA_PASSWORD: "Saqib123!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1437:1433"
    networks:
      - xptrackercs_db

volumes:
  db_data:

networks:
  nginx-proxy:
    external: true
  xptrackercs_db:
    internal: true