version: '3.4'

services:
  api:
    image: saqibrazzaq/xptrackercs_api
    container_name: xptrackercs_api
    build:
      context: .
      dockerfile: api/Dockerfile
    depends_on:
      - db

  web:
    image: saqibrazzaq/xptrackercs_web
    container_name: xptrackercs_web
    environment:
      VIRTUAL_HOST: xptrackercs-web.saqibrazzaq.com
      LETSENCRYPT_HOST: xptrackercs-web.saqibrazzaq.com
      LETSENCRYPT_EMAIL: "saqibrazzaq@gmail.com"
      CHOKIDAR_USEPOLLING: true
    build: 
      context: ./web
      #dockerfile: web/Dockerfile
      target: production
    expose:
      - 80
    stdin_open: true
    tty: true
    depends_on:
      - api
    networks:
      - nginx-proxy

  db:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: xptrackercs_db

networks:
  nginx-proxy:
    external: true
  xptrackercs_db:
    internal: true